<a href="https://colab.research.google.com/github/psharma521981/PythonLearning/blob/main/numpy_pandas/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
print(np.__version__)
print(pd.__version__)




array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(10)
cp = arr.copy()
cp[cp % 2 == 0] = 0
cp[cp % 2 == 1] = 1
cp

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [ ]:

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
b
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]
pd.describe_option

In [1]:
import numpy as np
#Dot Across numpy function

#a = np.array([1,2,3,4])
#b = np.array([5,6,7,8])

#A = np.sqrt(np.dot(a,a))
#print(A)
#B = np.sqrt(np.dot(b,b))
#print(B)
#t = np.arccos(np.dot(a,b)/(A*B))

#print(t*(180/np.pi))


a = np.array([1,0,0])
b = np.array([0,1,0])
print(np.dot(a,b))
t = np.arccos(0)
print(t)

0
1.5707963267948966


In [2]:
import numpy as np

# Matrix multiplication with non-similar dimensions
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c = np.array([10,100,1000])
d = np.array([10,11])

d = d.reshape((2,1))
d.shape
print(a*d)

#Calculate Unit vector
v = np.array((2, -4, 3))
u = v / np.sqrt((v*v).sum())
print(u)

#Vector transpose

[[10 20 30]
 [44 55 66]]
[ 0.37139068 -0.74278135  0.55708601]
