In [3]:
import numpy as np
import pandas as pd
print(np.__version__)
print(pd.__version__)




array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np.arange(10)
cp = arr.copy()
cp[cp % 2 == 0] = 0
cp[cp % 2 == 1] = 1
cp

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [11]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
b
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]
pd.describe_option